### ISSUE TITLE
UX Bug Bag 🐛

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-webgl-component#238]
# TODO
- [x] Consolidate isolation behavior:
  - Isolation action triggers:
    - "I" shortcut key
    - Right-click context menu > Isolate
    - Isolation button in the action bar
  - Upon isolation:
    - Check current selection.
        - If selection is different from current isolation set, frame the camera to the newly isolated set.
  - Upon toggling isolation:
    - If there is no selection OR if the selection is the same:
        - DO NOT MOVE THE CAMERA
        - Toggle the isolation display state
  - For any ambiguity, fall back to the desktop app behavior
- [x] Show/hide in project inspector should not move the camera.
- [x] Context menu "Zoom to Fit" should display "F" as its shortcut key
- [x] Context menu "Show/hide" should display "V" as its shortcut key (also implement this)
- [x] When zooming to fit small very objects (ex: sprinklers in Autodesk Hospital), the camera's front plane clips through the object. Possible solution: add a minimum distance at which the camera may approach the object.
