### ISSUE TITLE
VIM Web Open Source Monorepo

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-webgl-component#285]
# Goal

We want a single repository to improve iteration times on the WebGL viewer/component/vim ultra

# TODO

- [x] Provision new repository: **[vim-web](https://github.com/vimaec/vim-web)**
- [x] Update READMEs in older repos pointing to the vim-web repo
- [x] Update license.txt with: `Copyright 2024 VIMBuild, LLC`
- [x] Add .github/CODEOWNERS file with the contents: `* @vim-sroberge @mavimaec`
- [x] Add appropriate GitHub CI/CD checks to validate pull requests
- [x] Add appropriate GitHub actions to create and upload releases
  - [x] Add relevant secrets
- [x] Enable branch protection rules
- [x] Deliverable from **vim-web**: VIM Web NPM Package
- [x] Add/update documentation in vim-docs
- [x] Add vim-web as submodule to vim-renderer for testing/iteration purposes in VIM Ultra
- [x] Add deprecation messaging in NPM on old packages indicating new location/package
- [x] Create a new pbi visual version based on vim-web
